--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CosmicDevTeam/AmazingSell
build-by-default: true
branches:
- main
projects:
  AmazingSell:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
      - src: CortexPE/Commando/Commando
        
  
...
