name: AmazingSell
author: IamFxr.lol
main: zephy\sell\Loader
api: 5.0.0
version: 1.0.0

permissions:
   amazingsell.default.permission:
      default: true
   amazingsell.admin.permission:
      default: op